name: Hit Cron API

on:
  schedule:
    - cron: "43 19 * * *"  # 1:13 AM IST
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Hit API
        run: |
          curl "https://follopay.free.nf/api/deactivate-posts.php?key=my_super_secret_12345"
          
